/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/fibonacci_spiral_detection.glb -o components/3d/fibonacci.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d_models/fibonacci_spiral_detection.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Empty001.geometry} material={materials.Empty} rotation={[-Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/3d_models/fibonacci_spiral_detection.glb')
