/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/3d_models/chibi.glb -o components/3d/chibi.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d_models/chibi.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002.geometry} material={materials['front_walking_1024x1024.gif.001_mesh.001']} position={[0, 0.192, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.979} />
      {/* <mesh geometry={nodes.Cube003.geometry} material={materials['Material.004']} position={[0.021, -0.897, -0.064]} scale={[1, 0.05, 1]} /> */}
      {/* <mesh geometry={nodes.Cube004.geometry} material={materials['Material.005']} position={[0.021, -1.016, -0.064]} scale={[1.15, 0.057, 1.15]} /> */}
    </group>
  )
}

useGLTF.preload('/3d_models/chibi.glb')
