/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/3d_models/fibonacci_logo.glb -o components/3d/fibonacci.jsx 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/3d_models/fibonacci_logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane001.geometry} material={materials['logo.png_mesh'] } rotation={[0, 0.45 * Math.PI / 2, -1* Math.PI/2]}/>
    </group>
  )
}

useGLTF.preload('/3d_models/fibonacci_logo.glb')
